services:
  - type: web
    name: yachachiy-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:2121146800R$.@db.fmcxwoqvxatbrawwtqke.supabase.co:5432/postgres
      - key: PYTHONPATH
        value: .
